### PR TITLE
Bug: Failure on enhanced nav - reproduced

### PR DESCRIPTION
**Pull request by garrettlondon1**
Navigate to the counter page - htmx will be loaded

Double Click on the counter page again in the navmenu - htmx will not be loaded

same enhancedload event is triggered

Any solution to this?

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
~~This looks like a Blazor bug. If you look at the response in the Web Dev Tools it shows and error being returned from Blazor, so when we call `htmx.process(document.body)` the `hx-*` elements are not there to begin with. Hope this helps you find the issue.~~

Turns out it was an issue in HTMX. I updated to the latest version and it seems to work consistently now. The Blazor error is a read hearing, since it's always passed back in a hidden element. Try this.

Step 1. Update HTMX from `1.9.8` to `1.9.12`

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <base href="/"/>
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css"/>
    <link rel="stylesheet" href="app.css"/>
    <link rel="stylesheet" href="BlazorHtmx.styles.css"/>
    <link rel="icon" type="image/png" href="favicon.png"/>

    <script defer src="_framework/blazor.web.js"></script>
    <script defer src="https://unpkg.com/htmx.org@1.9.12"></script>
    <script defer src="js/htmx-blazor.js"></script>
    <HeadOutlet/>
</head>
<body>
<Routes/>
</body>
</html>
```

Step 2. Run the app.

Note: There still seems to be an issue if someone clicks like a maniac on the navigation, but I wouldn't expect anyone to do that (I hope at least. 😅)

**Comment by garrettlondon1** [comment]
That didn't work for me unfortunately. Navigating to the counter still produces an empty result in the target div even with 1.9.12.

**Comment by garrettlondon1** [comment]
Are you double clicking on the counter in the NavBar?

**Comment by khalidabuhakmeh** [comment]
I came back to this and figured it out this time. It's Blazor's fault. Let me explain.

The `load` event is only triggered when the page loads or the elements load on the page. Calling `htmx.process` will only apply to changed nodes.

Blazor is doing some kind of virtual-dom diffing with enhanced load, meaning in your sample, the search bar is never replaced on the second navigation click. Watch this video.

https://github.com/khalidabuhakmeh/BlazorHtmx/assets/228256/8ef020fd-61fb-49d2-b40f-d5febf28bbca

Since the event in your `hx-trigger="load, input changed delay:200ms"`, yeah it is never "reloaded" so it doesn't fire on subsequent clicks unless the element is newer or swapped in.

Let's test this theory out by changing the element so it's **always** new. (note the `data-cache`).

```
        <input hx-get="/search"
               hx-trigger="load, input changed delay:200ms"
               hx-swap="innerHTML" type="text" name="searchParam" placeholder="Search..." autocomplete="off"
               class="focus:ring-emerald-500 focus:border-emerald-500 block w-full shadow-sm text-sm border-gray-300 rounded-md"
               data-cache="@Guid.NewGuid().ToString("N")"
               >
```

https://github.com/khalidabuhakmeh/BlazorHtmx/assets/228256/c26b5b8f-f251-4f40-9d6e-cd6131dea720

So, there you have it. The issue is Blazor and how it swaps elements in.

My recommendation is not to trigger on `load` but to render the results in the response. 

I tried this approach from Alexander (https://alexanderzeitler.com/articles/listening-to-htmx-hx-trigger-response-header-events-from-alpine-js/) but Blazor seems intent on fighting my ability to add headers to responses.

Hope this helps. Cheers :)

**Comment by garrettlondon1** [comment]
Thank you so much! I had a feeling it was Blazor diff swapping as well

**Comment by khalidabuhakmeh** [comment]
I'm going to close this issue. Best of luck with Blazor. This seems like a tough cookie to crack.

**Pull request closed without merging**
